name: Create Dev Test and Prod Environments
# clean up the environment for the next demo
#  clean up environment tasks for QA and Prod 

on:
  workflow_dispatch:
    inputs:
    
     env_name:
       description: name for the environment to be created
       required: true
       default: GitHub Actions Demo
     
     client_id:
       description: service principal client id
       required: true
      
     user_id:
       description: AAD object id for the user
       required: true

     domain:
       description: domain used with your environment 
       required: true
       default: GitHubActionsDemo
   
 #Do Not change these values
permissions:
  contents: write      

jobs:
 
  Create-Environments:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    #- name: Script
     # run: ./script.ps1
      #shell: pwsh
      
    - name: Create Sandbox Environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        app-id: '0f1aaa86-6311-4b76-ad49-cbc028f3096f'
        client-secret: ${{ secrets.DEV_APP_SECRET }}
        tenant-id: '65f3cfd5-0a49-4a5e-8bf4-f8ca438a9fda'
        name: ${{ github.event.inputs.env_name}}_SB
        type: Sandbox
        domain: ${{ github.event.inputs.domain}}SB
    
    - name: assign-user to sandbox environment
      uses:  microsoft/powerplatform-actions/assign-user@v0
      with:
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        environment: 'https://${{ github.event.inputs.env_name}}Dev.dynamics.com'
        user: ${{ github.event.inputs.user_id }}
        role: System Administrator
        
    #- name: Create Test Environment
    #  uses: microsoft/powerplatform-actions/create-environment@v0
    #    with:
    #      app-id: ${{secrets.CLIENT_ID}}
     #     client-secret: ${{ secrets.PowerPlatformSPN }}
     #     tenant-id: ${{secrets.TENANT_ID}}
     #     name: ${{ github.event.inputs.env_name}}_Test
     #     type: Sandbox
     #     domain: ${{ github.event.inputs.domain}}Test

    #  - name: assign-user to test environment
    #    uses:  microsoft/powerplatform-actions/assign-user@v0
   #     with:
    #      app-id: ${{secrets.CLIENT_ID}}
    #      client-secret: ${{ secrets.PowerPlatformSPN }}
     #     tenant-id: ${{secrets.TENANT_ID}}
     #     environment: 'https://${{ github.event.inputs.env_name}}Test.crm.dynamics.com'
      #    user: ${{ github.event.inputs.user_id }}
     #     role: System Administrator
        
        
  #    - name: Create Production Environment
   #     uses: microsoft/powerplatform-actions/create-environment@v0
   #     with:
   #       app-id: ${{secrets.CLIENT_ID}}
   #       client-secret: ${{ secrets.PowerPlatformSPN }}
   #       tenant-id: ${{secrets.TENANT_ID}}
   #       name: ${{ github.event.inputs.env_name}}_Prod
   #       type: Production
   #       domain: ${{ github.event.inputs.env_name}}Prod

  #    - name: assign-user to Prod environment
  #      uses:  microsoft/powerplatform-actions/assign-user@v0
 #       with:
  #        app-id: ${{secrets.CLIENT_ID}}
   #       client-secret: ${{ secrets.PowerPlatformSPN }}
   #       tenant-id: ${{secrets.TENANT_ID}}
    #      environment: 'https://${{ github.event.inputs.env_name}}Prod.crm.dynamics.com'
   #       user: ${{ github.event.inputs.user_id }}
    #      role: System Administrator
